#!/usr/bin/env bash
# 301 Permanent Redirection

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Allow HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Path to the Nginx configuration file
NGINX_CONF="/etc/nginx/sites-available/default"

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

string="server_name _;"
string+="\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s@server_name _;@$string@" $NGINX_CONF

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
