#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create the custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Define the Nginx configuration file
NGINX_CONF="/etc/nginx/sites-available/default"

# Use sed to insert the custom 404 error page configuration
sudo sed -i '/server {/a \
    error_page 404 /custom_404.html;\
    location = /custom_404.html {\
        internal;\
    }' $NGINX_CONF

sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart
