#!/usr/bin/env bash
# 404 Page Not Found

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Allow HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create the custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Specify the target URL for redirection
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Path to the Nginx configuration file
NGINX_CONF="/etc/nginx/sites-available/default"

# Add the redirection configuration using sed
sudo sed -i "/server {/a \    location \/redirect_me {\n        return 301 $REDIRECT_URL;\n    }" $NGINX_CONF

# Use sed to insert the custom 404 error page configuration
sudo sed -i '/server {/a \
    error_page 404 /custom_404.html;\
    location = /custom_404.html {\
        internal;\
    }' $NGINX_CONF

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
