#!/usr/bin/env bash
# Install and configure HAProxy as a reverse proxy and load balancer

# Update and upgrade the system
sudo apt-get -y update && sudo apt-get -y upgrade

# Install necessary packages
sudo apt-get install -y --no-install-recommends software-properties-common

# Add the correct PPA for HAProxy 2.4
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4

# Update the package lists
sudo apt-get update -y

# Install HAProxy from the added PPA
sudo apt-get install -y haproxy=2.4.\*


CONF="/etc/haproxy/haproxy.cfg"

# Configure HAProxy as a load balancer and reverse proxy
echo "
frontend my_frontend
    bind *:80
    mode http
    default_backend nginx_backend

backend nginx_backend
    balance roundrobin
    mode http
    server 499808-web-01 18.235.243.79:80 check
    server 499808-web-02 34.207.57.119:80 check" >> $CONF

# Restart HAProxy
sudo service haproxy restart
