#!/usr/bin/env bash
# Install and configure HAProxy as a reverse proxy and load balancer

# Update and upgrade the system
sudo apt-get -y update && sudo apt-get -y upgrade

# Install haproxy
sudo apt-get install -y haproxy

CONF="/etc/haproxy/haproxy.cfg"

# Configure HAProxy as a load balancer and reverse proxy
echo "
frontend my_frontend
    bind *:80
    mode http
    default_backend nginx_backend

backend nginx_backend
    balance roundrobin
    mode http
    server 499808-web-01 18.235.243.79:80 check
    server 499808-web-02 34.207.57.119:80 check" >> $CONF

# Restart HAProxy
sudo service haproxy restart
