#!/usr/bin/env bash
# this script:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Step1: create file
file="/var/run/myscript.pid"

# file has its own pid
echo "$$" > "$file"

# step3: SIGTERM, I hate the kill command
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

# step 4: SIGINT, Y U no love me?!
trap "echo Y U no love me?!" SIGINT

# step2: infinite loop
while ((1))
do
	echo "To infinity and beyond"
	sleep 1
done
