#!/usr/bin/env bash
# this script displays numbers from 1 to 100.
# FizzBuzz when the number is a multiple of 3 and 5
# Fizz when the number is multiple of 3
# Buzz when the number is a multiple of 5
# Otherwise, displays the number

x=1
while ((x <= 100))
do
if [ $((x % 3)) -eq 0 ] && [ $((x % 5)) -eq 0 ]
then
	echo "FizzBuzz"
elif [ $((x % 3)) -eq 0 ]
then
	echo "Fizz"
elif [ $((x % 5)) -eq 0 ]
then
	echo "Buzz"
else
	echo "$x"
fi
((x++))
done
