#!/usr/bin/env bash
# Displays the visitor IP along with the HTTP status code from the Apache log file

logfile="apache-access.log"

# $1 extracts the first field, Visitor IP
# $9 extracts the status code
# awk used to parse the log file

awk -F' ' '{print $1, $9}' $logfile
