#!/usr/bin/env bash
# this script displays "Best School" ten times
#+ using the while command

# initialize x to 0
x=0

#use comparison operator lt
while [ $x -lt 10 ]; do
	echo "Best School"
	((x++))
done
