#!/usr/bin/env bash
# this script displays Best School ten times
# but on the 9th iteration, prints Hi after Best School

x=1
while ((x <= 10))
do
	echo "Best School"
	if ((x == 9))
	then
		echo "Hi"
	fi
	((x++))
done
