#!/usr/bin/env bash
# this script displays the time for 12 hours and 59 minutes
#+ display hours from 0 to 12
#+ display minutes from 1 to 59

hour=0
while ((hour <= 12))
do
	echo "Hour: $hour"
	# initialize min variable for the minutes
	min=1
	while ((min <= 59))
	do
		echo "$min"
		# increment min
		((min++))
		done
	# increment hour
	((hour++))
done		
