#!/usr/bin/env bash
# this script gives information about the "school" file.
# check if the file exists and prints:
#+ if the file exists: school file exists
#+ if the file does not exist: school file does not exist

# If the file exists, print:
#+ if the file is empty: school file is empty
#+ if the file is not empty: school file is not empty
#+ if the file is a regular file: school is a regular file
#+ if the file is not a regular file: (nothing)

if [ -e "school" ]
then
	echo "school file exists"
	
	# check size
	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	
	# check if it is a regular file
	if [ -f "school" ]
	then
		echo "school is a regular file"
	fi
# if file does not exist
else
	echo "school file does not exist"
fi
